### ISSUE TITLE
获取章节出错 大佬能看看吗

### ISSUE THREAD

**Issue by buding9527** [ZeroMapleQvQ/ILP#1]
![image](https://github.com/user-attachments/assets/61728e3f-3ffe-4e34-8aeb-991119cee9d0)

**Comment by RhenCloud** [comment]
此问题应该已在[4374e55](https://github.com/ZeroMapleQvQ/ILP/commit/4374e5563a987c408fbc6ddada932bbb82509aa8)中修复

**Comment by buding9527** [comment]
> 此问题应该已在[4374e55](https://github.com/ZeroMapleQvQ/ILP/commit/4374e5563a987c408fbc6ddada932bbb82509aa8)中修复

新版本输入指令之后不起效

**Comment by buding9527** [comment]
> 此问题应该已在[4374e55](https://github.com/ZeroMapleQvQ/ILP/commit/4374e5563a987c408fbc6ddada932bbb82509aa8)中修复

![image](https://github.com/user-attachments/assets/5f0ed924-0924-4070-9a76-da44cf4370a4)

**Comment by RhenCloud** [comment]
> > 此问题应该已在[4374e55](https://github.com/ZeroMapleQvQ/ILP/commit/4374e5563a987c408fbc6ddada932bbb82509aa8)中修复
> 
> ![image](https://private-user-images.githubusercontent.com/95774949/367561756-5f0ed924-0924-4070-9a76-da44cf4370a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzODQzMzksIm5iZiI6MTcyNjM4NDAzOSwicGF0aCI6Ii85NTc3NDk0OS8zNjc1NjE3NTYtNWYwZWQ5MjQtMDkyNC00MDcwLTlhNzYtZGE0NGNmNDM3MGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDA3MDcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzNzA1MTFhNjgwYjNjOGQxMjYwNjRkNDFkNmE3YTk4Nzg2YTQ4NThiMTIyMGI5MjRjMDI3YmE5MjMwYjg5NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HPfMtPJi-0CpcPywOZJHwN3JtMMcfNHRJKkbdqJ9UhM)

由于番茄小说api接口变更，目前暂时无法爬取番茄小说正文，正在积极进行修复中

**Comment by RhenCloud** [comment]
@buding9527 在release v1.1.0中添加了自定义cookie的功能,修复了番茄小说的爬取
